// <auto-generated />
using System;
using Common.Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Core.Migrations
{
    [DbContext(typeof(MedicalInsuranceDbContext))]
    [Migration("20260624085241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Common.Core.Entities.ExceptionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exception_message");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("exception_type");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text")
                        .HasColumnName("request_body");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("request_path");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("service_name");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExceptionType");

                    b.HasIndex("ServiceName");

                    b.ToTable("exception_log");
                });

            modelBuilder.Entity("Common.Core.Entities.Heartbeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastHeartbeatTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_heartbeat_time");

                    b.Property<string>("ServiceIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("service_ip");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("service_name");

                    b.Property<int>("ServicePort")
                        .HasColumnType("int")
                        .HasColumnName("service_port");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatTime");

                    b.HasIndex("ServiceName");

                    b.HasIndex("Status");

                    b.ToTable("heartbeat");
                });

            modelBuilder.Entity("Common.Core.Entities.SettlementRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("city_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal>("MedicalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("medical_amount");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("patient_name");

                    b.Property<string>("RecordNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("record_no");

                    b.Property<decimal>("SelfPayAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("self_pay_amount");

                    b.Property<string>("SettlementStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("settlement_status");

                    b.Property<string>("ThirdPartyResponse")
                        .HasColumnType("text")
                        .HasColumnName("third_party_response");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CityCode");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PatientId");

                    b.HasIndex("RecordNo")
                        .IsUnique();

                    b.HasIndex("SettlementStatus");

                    b.ToTable("settlement_record");
                });
#pragma warning restore 612, 618
        }
    }
}
